export const iconSet: Record<string, string> = {
  // For labels
  feelslike: "thermostat",
  humidity: "humidity_mid",
  windspeed: "air",
  cloudcover: "filter_drama",
  sunrise: "water_lux",
  sunset: "wb_twilight",
  precip: "rainy",

  // For weather conditions
  Clear: "clear_day",
  Sunny: "clear_day",
  "Partly Cloudy": "partly_cloudy_day",
  "Mostly Cloudy": "cloud",
  Overcast: "foggy",
  Rain: "rainy",
  "Light Rain": "rainy",
  "Heavy Rain": "thunderstorm",
  Thunderstorm: "thunderstorm",
  Snow: "snowing",
  "Light Snow": "snowing",
  "Heavy Snow": "snowing_heavy",
  Haze: "foggy",
  Fog: "foggy",
  Windy: "cloud",
  Blustery: "cloud",
  Hail: "thunderstorm",
  Sleet: "snowing",
  Tornado: "thunderstorm",
  Hurricane: "thunderstorm",
  Sandstorm: "cloud",
  Dust: "cloud",
  Smoke: "cloud",
  "Freezing Rain": "rainy_snow",
};
